# Generated by Django 6.0 on 2026-01-03 18:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descrição')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço')),
                ('is_active', models.BooleanField(default=False, verbose_name='ativo')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='posição')),
                ('picture', models.ImageField(help_text='Imagem principal do produto.', upload_to='products/images/', verbose_name='imagem')),
                ('thumbnail', models.ImageField(help_text='Imagem quadrada de 85x85 pixels.', upload_to='products/thumbnails/', verbose_name='miniatura')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.store', verbose_name='loja')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
                'db_table': 'product',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title', models.CharField(max_length=100, verbose_name='título')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='posição')),
                ('type', models.CharField(choices=[('grid', 'grade'), ('list', 'lista'), ('slider', 'slider')], default='grid', max_length=50, verbose_name='tipo')),
                ('is_active', models.BooleanField(default=False, verbose_name='ativo')),
                ('is_required', models.BooleanField(default=False, verbose_name='obrigatório')),
                ('is_highlighted', models.BooleanField(default=False, verbose_name='destacado')),
                ('form', models.CharField(choices=[('checkbox', 'selecionar mais de um'), ('radio', 'selecionar apenas um'), ('textbox', 'observação'), ('increment_decrement', 'incrementar/decrementar')], default='checkbox', max_length=50, verbose_name='formulário')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='store.store', verbose_name='loja')),
            ],
            options={
                'verbose_name': 'seção',
                'verbose_name_plural': 'seções',
                'db_table': 'section',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ProductSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='posição')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sections', to='product.product')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_products', to='product.section')),
            ],
            options={
                'verbose_name': 'Seção do Produto',
                'verbose_name_plural': 'Seções dos Produtos',
                'db_table': 'through_product_sections',
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.section', verbose_name='seção'),
        ),
        migrations.AddField(
            model_name='product',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='products_many', through='product.ProductSections', to='product.section', verbose_name='seções'),
        ),
    ]
