# Generated by Django 6.0 on 2026-01-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='type',
        ),
        migrations.AddField(
            model_name='section',
            name='max_products',
            field=models.PositiveIntegerField(default=0, verbose_name='máximo de produtos'),
        ),
        migrations.AddField(
            model_name='section',
            name='min_products',
            field=models.PositiveIntegerField(default=0, verbose_name='mínimo de produtos'),
        ),
        migrations.AddField(
            model_name='section',
            name='textbox_help_text',
            field=models.CharField(blank=True, help_text='Texto de ajuda exibido abaixo do campo de observação.', max_length=255, null=True, verbose_name='texto de ajuda'),
        ),
        migrations.AlterField(
            model_name='section',
            name='form',
            field=models.CharField(choices=[('checkbox', 'Selecionar mais de um'), ('radio', 'Selecionar apenas um'), ('textbox', 'Observação'), ('increment_decrement', 'Incrementar/Decrementar')], default='checkbox', max_length=50, verbose_name='formulário'),
        ),
        migrations.AlterField(
            model_name='section',
            name='is_highlighted',
            field=models.BooleanField(default=False, verbose_name='destaque'),
        ),
    ]
