# Generated by Django 6.0 on 2026-01-03 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_section_type_section_max_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='preço'),
        ),
        migrations.AlterField(
            model_name='product',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.section', verbose_name='seção'),
        ),
        migrations.AlterField(
            model_name='section',
            name='form',
            field=models.CharField(choices=[('not_applicable', 'N/A'), ('checkbox', 'Selecionar mais de um'), ('radio', 'Selecionar apenas um'), ('textbox', 'Observação'), ('increment_decrement', 'Incrementar/Decrementar')], default='not_applicable', max_length=50, verbose_name='formulário'),
        ),
    ]
