# Generated by Django 6.0 on 2026-01-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_price_alter_product_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentagem de desconto aplicada ao preço do produto.', max_digits=5, verbose_name='porcentagem de desconto'),
        ),
        migrations.AlterField(
            model_name='section',
            name='form',
            field=models.CharField(choices=[('not_applicable', 'N/A'), ('checkbox', 'Mais de um'), ('radio', 'Apenas um'), ('textbox', 'Observação'), ('increment_decrement', 'Incrementar/Decrementar')], default='not_applicable', max_length=50, verbose_name='formulário'),
        ),
    ]
