# Generated by Django 6.0 on 2026-01-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_discount_percentage_alter_section_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentagem de desconto aplicada ao preço do produto. Para um desconto de 10%, insira 10.00.', max_digits=5, verbose_name='porcentagem de desconto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Define a ordem de exibição dos produtos na seção.', verbose_name='posição'),
        ),
        migrations.AlterField(
            model_name='productsections',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='posição'),
        ),
        migrations.AlterField(
            model_name='section',
            name='form',
            field=models.CharField(choices=[('not_applicable', 'N/A'), ('radio', 'Apenas um'), ('increment_decrement', 'Incrementar/Decrementar'), ('textbox', 'Observação')], default='not_applicable', max_length=50, verbose_name='formulário'),
        ),
        migrations.AlterField(
            model_name='section',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='posição'),
        ),
        migrations.AlterField(
            model_name='section',
            name='textbox_help_text',
            field=models.CharField(blank=True, help_text='Texto de ajuda exibido abaixo do campo de observação. Exemplo: tirar a cebola, maionese à parte etc.', max_length=255, null=True, verbose_name='texto de ajuda'),
        ),
    ]
