# Generated by Django 6.0 on 2026-01-17 22:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('delivering', 'Entregando'), ('completed', 'Concluído'), ('canceled', 'Cancelado')], default='pending', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='observações')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='taxa de entrega')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='subtotal')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='total')),
                ('zip_code', models.CharField(db_index=True, max_length=8, verbose_name='CEP')),
                ('street', models.CharField(max_length=255, verbose_name='logradouro')),
                ('number', models.CharField(max_length=20, verbose_name='número')),
                ('neighborhood', models.CharField(max_length=255, verbose_name='bairro')),
                ('complement', models.CharField(blank=True, max_length=255, null=True, verbose_name='complemento')),
                ('reference', models.CharField(blank=True, max_length=255, null=True, verbose_name='referência')),
                ('city', models.CharField(max_length=255, verbose_name='cidade')),
                ('state', models.CharField(max_length=2, verbose_name='UF')),
                ('latitude', models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='account.account', verbose_name='cliente')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='store.store', verbose_name='loja')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'db_table': 'order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('product_uuid', models.UUIDField(verbose_name='UUID do produto')),
                ('product_name', models.CharField(max_length=255, verbose_name='nome do produto')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço unitário')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantidade')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'item do pedido',
                'verbose_name_plural': 'itens do pedido',
                'db_table': 'order_item',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('order', 'product_uuid'), name='unique_product_per_order')],
            },
        ),
    ]
