# Generated by Django 6.0 on 2026-01-13 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_address_reference_alter_address_label'),
        ('order', '0001_initial'),
        ('store', '0002_alter_store_delivery_fee_alter_store_min_order_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='account.account', verbose_name='cliente'),
        ),
        migrations.AlterField(
            model_name='order',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='store.store', verbose_name='loja'),
        ),
    ]
