# Generated by Django 6.0 on 2026-01-03 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deletado em')),
                ('uuid', models.CharField(max_length=36, unique=True, verbose_name='UUID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('cnpj', models.CharField(max_length=14, unique=True, verbose_name='CNPJ')),
                ('thumbnail', models.ImageField(help_text='Imagem quadrada de 75x75 pixels.', upload_to='stores/thumbnails/', verbose_name='miniatura')),
                ('banner', models.ImageField(help_text='Imagem retangular de 1296x200 pixels.', upload_to='stores/banners/', verbose_name='banner')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Configurações da loja em formato JSON.', null=True, verbose_name='configuração')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to='account.account', verbose_name='dono')),
            ],
            options={
                'verbose_name': 'loja',
                'verbose_name_plural': 'lojas',
                'db_table': 'store',
            },
        ),
    ]
