# Generated by Django 6.0 on 2026-01-17 22:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(help_text='Nome legal da loja.', max_length=100, verbose_name='nome')),
                ('fantasy_name', models.CharField(help_text='Nome de divulgação da loja.', max_length=100, verbose_name='nome fantasia')),
                ('slug', models.SlugField(help_text='Gerado automaticamente a partir do nome fantasia.', max_length=100, verbose_name='slug')),
                ('cnpj', models.CharField(max_length=14, unique=True, verbose_name='CNPJ')),
                ('thumbnail', models.ImageField(help_text='Imagem quadrada de 75x75 pixels.', upload_to='stores/thumbnails/', verbose_name='miniatura')),
                ('banner', models.ImageField(help_text='Imagem retangular de 1920x1080 pixels.', upload_to='stores/banners/', verbose_name='banner')),
                ('min_order_value', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor mínimo do pedido. Em reais (R$). Ex: 9.99', max_digits=10, verbose_name='valor mínimo do pedido')),
                ('delivery_time', models.PositiveIntegerField(default=60, help_text='Tempo estimado de entrega em minutos.', verbose_name='tempo de entrega')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Taxa fixa cobrada por entrega. Em reais (R$). Ex: 9.99', max_digits=10, verbose_name='taxa de entrega')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='account.account', verbose_name='dono')),
            ],
            options={
                'verbose_name': 'loja',
                'verbose_name_plural': 'lojas',
                'db_table': 'store',
            },
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado'), (7, 'Domingo')], verbose_name='dia da semana')),
                ('from_hour', models.TimeField(verbose_name='abre às')),
                ('to_hour', models.TimeField(verbose_name='fecha às')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='store.store', verbose_name='loja')),
            ],
            options={
                'verbose_name': 'horário de funcionamento',
                'verbose_name_plural': 'horários de funcionamento',
                'db_table': 'opening_hours',
                'ordering': ('weekday', 'from_hour'),
                'constraints': [models.CheckConstraint(condition=models.Q(('from_hour__lt', models.F('to_hour'))), name='opening_hours_from_lt_to'), models.UniqueConstraint(fields=('store', 'weekday'), name='opening_hours_unique_interval')],
            },
        ),
    ]
