# Generated by Django 6.0 on 2026-01-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Taxa fixa cobrada por entrega. Em reais (R$). Ex: 9.99', max_digits=10, verbose_name='taxa de entrega'),
        ),
        migrations.AlterField(
            model_name='store',
            name='min_order_value',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor mínimo do pedido. Em reais (R$). Ex: 9.99', max_digits=10, verbose_name='valor mínimo do pedido'),
        ),
    ]
