# Generated by Django 6.0 on 2026-01-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_store_delivery_fee_alter_store_min_order_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='delivery_time',
            field=models.PositiveIntegerField(default=60, help_text='Tempo estimado de entrega em minutos.', verbose_name='tempo de entrega'),
        ),
    ]
