# Generated by Django 6.0 on 2026-01-17 22:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('type', models.CharField(choices=[('client', 'Cliente'), ('admin', 'Administrador')], max_length=10, verbose_name='tipo')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('phone', models.CharField(max_length=13, unique=True, verbose_name='telefone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'conta',
                'verbose_name_plural': 'contas',
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('label', models.CharField(blank=True, help_text='Ex: Casa, Trabalho, Matriz, Filial', max_length=50, null=True, verbose_name='rótulo')),
                ('is_default', models.BooleanField(default=False, help_text='Endereço principal.', verbose_name='padrão')),
                ('zip_code', models.CharField(db_index=True, max_length=8, verbose_name='CEP')),
                ('street', models.CharField(max_length=255, verbose_name='logradouro')),
                ('number', models.CharField(max_length=20, verbose_name='número')),
                ('neighborhood', models.CharField(max_length=255, verbose_name='bairro')),
                ('complement', models.CharField(blank=True, max_length=255, null=True, verbose_name='complemento')),
                ('reference', models.CharField(blank=True, max_length=255, null=True, verbose_name='referência')),
                ('city', models.CharField(max_length=255, verbose_name='cidade')),
                ('state', models.CharField(max_length=2, verbose_name='UF')),
                ('latitude', models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='account.account', verbose_name='conta')),
            ],
            options={
                'verbose_name': 'endereço',
                'verbose_name_plural': 'endereços',
                'db_table': 'address',
            },
        ),
    ]
