# Generated by Django 6.0 on 2026-01-12 22:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('store', '0002_alter_store_delivery_fee_alter_store_min_order_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('label', models.CharField(blank=True, help_text='Ex: Casa, Trabalho, Matriz, Filial', max_length=50, null=True, verbose_name='apelido')),
                ('is_default', models.BooleanField(default=False, help_text='Endereço principal.', verbose_name='padrão')),
                ('zip_code', models.CharField(db_index=True, max_length=8, verbose_name='CEP')),
                ('street', models.CharField(max_length=255, verbose_name='logradouro')),
                ('number', models.CharField(max_length=20, verbose_name='número')),
                ('neighborhood', models.CharField(max_length=255, verbose_name='bairro')),
                ('complement', models.CharField(blank=True, max_length=255, null=True, verbose_name='complemento')),
                ('city', models.CharField(max_length=255, verbose_name='cidade')),
                ('state', models.CharField(max_length=2, verbose_name='UF')),
                ('latitude', models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='account.account', verbose_name='conta')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='store.store', verbose_name='loja')),
            ],
            options={
                'verbose_name': 'endereço',
                'verbose_name_plural': 'endereços',
                'db_table': 'address',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('account__isnull', False), ('store__isnull', True)), models.Q(('account__isnull', True), ('store__isnull', False)), _connector='OR'), name='address_owner_xor_account_store'), models.CheckConstraint(condition=models.Q(('zip_code__regex', '^\\d{8}$')), name='address_zipcode_8_digits'), models.CheckConstraint(condition=models.Q(('state__regex', '^[A-Z]{2}$')), name='address_state_uf_format'), models.UniqueConstraint(condition=models.Q(('is_default', True), ('account__isnull', False)), fields=('account',), name='unique_default_address_per_account'), models.UniqueConstraint(condition=models.Q(('is_default', True), ('store__isnull', False)), fields=('store',), name='unique_default_address_per_store')],
            },
        ),
    ]
