# Generated by Django 6.0 on 2026-01-17 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='store.store', verbose_name='loja'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('account__isnull', False), ('store__isnull', True)), models.Q(('account__isnull', True), ('store__isnull', False)), _connector='OR'), name='address_owner_xor_account_store'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.CheckConstraint(condition=models.Q(('zip_code__regex', '^\\d{8}$')), name='address_zipcode_8_digits'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.CheckConstraint(condition=models.Q(('state__regex', '^[A-Z]{2}$')), name='address_state_uf_format'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True), ('account__isnull', False)), fields=('account',), name='unique_default_address_per_account'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True), ('store__isnull', False)), fields=('store',), name='unique_default_address_per_store'),
        ),
    ]
