# Generated by Django 6.0 on 2026-01-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='referência'),
        ),
        migrations.AlterField(
            model_name='address',
            name='label',
            field=models.CharField(blank=True, help_text='Ex: Casa, Trabalho, Matriz, Filial', max_length=50, null=True, verbose_name='rótulo'),
        ),
    ]
